### ISSUE TITLE
Type of property 'client' circularly references itself in mapped type 'EntityDTO<Loaded<Event<?>, any>>'

### ISSUE THREAD

**Issue by micchickenburger** [mikro-orm/mikro-orm#3509]
**Describe the bug**

After updating from mikro-orm from v5.2.4 to v5.4.2 I'm getting a strange Typescript compilation error:

```
Type of property 'events' circularly references itself in mapped type 'EntityDTO<Client & { name: string; events: Collection<Event<Client>, object> & LoadedCollection<Loaded<Event<Client>, never>>; ... 13 more ...; setSchema: ((schema?: string | undefined) => void) & {}; }>'.     ts(2615)
```

I have class Event that has a ManyToOne relationship with Client on `Client.events`.

```typescript
@Entity()
class Event<T> extends BaseEntity<Event<T>> {
  // ...

  @Property({ persist: false })
  get entity() {
    return this.client || this.user; // error occurs here
  }

  @ManyToOne()
    client?: Client;

  @ManyToOne()
    user?: User;

  // ...
}

@Entity()
class Client extends BaseEntity<Client> {
  // ...

  @OneToMany(() => Event<Client>, (event) => event.client)
    events = new Collection<Event<Client>>(this);

  // ...
}
```

**Expected behavior**
This same code worked before updating, so I wonder if some recent changes on types have caused Typescript to detect this circular dependency as a problem.  Expected behavior was as prior.

**Versions**

| Dependency | Version |
| - | - |
| node | v16.16.0 |
| typescript | v4.7.4 & 4.8.3 |
| mikro-orm | 5.4.2 |
| postgresql driver | 5.4.2 |
