### ISSUE TITLE
[5.4] IdentifiedReferences

### ISSUE THREAD

**Issue by roderik** [mikro-orm/mikro-orm#3445]
**Describe the bug**

Upgrading to 5.4 breaks IdentifiedReferences and toReference
This works in 5.3 and before

**Stack trace**

```
  @ExternalField(() => User)
  @ManyToOne('User', { wrappedReference: true, nullable: true })
  @Index()
  public owner: IdentifiedReference<User, 'id' | '_id'>;
```

```
error TS2322: Type '{ _id: ObjectId; id: string; } & Reference<AbstractEntity<"createdAt" | "updatedAt">>' is not assignable to type '{ _id: ObjectId; id: string; } & Reference<User>'.
             Type '{ _id: ObjectId; id: string; } & Reference<AbstractEntity<"createdAt" | "updatedAt">>' is not assignable to type 'Reference<User>'.
               Types of property 'load' are incompatible.
                 Type '{ <K extends keyof AbstractEntity<"createdAt" | "updatedAt"> = never, P extends string = never>(options?: LoadReferenceOptions<AbstractEntity<"createdAt" | "updatedAt">, P> | undefined): Promise<...>; <K extends keyof AbstractEntity<...>>(prop: K): Promise<...>; }' is not assignable to type '{ <K extends keyof User = never, P extends string = never>(options?: LoadReferenceOptions<User, P> | undefined): Promise<User>; <K extends keyof User>(prop: K): Promise<...>; }'.
                   Types of parameters 'options' and 'options' are incompatible.
                     Type 'LoadReferenceOptions<User, any> | undefined' is not assignable to type 'LoadReferenceOptions<AbstractEntity<"createdAt" | "updatedAt">, any> | undefined'.
                       Type 'LoadReferenceOptions<User, any>' is not assignable to type 'LoadReferenceOptions<AbstractEntity<"createdAt" | "updatedAt">, any>'.
                         Type '"createdAt" | "updatedAt" | "creditWarningSent" | "featureFlags" | "userState" | "permissions" | "themePreference" | "languagePreference" | undefined' is not assignable to type '"createdAt" | "updatedAt" | undefined'.
                           Type '"creditWarningSent"' is not assignable to type '"createdAt" | "updatedAt" | undefined'.
       
           72     this.owner = owner.toReference();
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16 |
| typescript | 4.8.2 |
| mikro-orm | 5.4.0 |
| mongodb | 4.9.1 |

**Comment by B4nan** [comment]
Not reproducible, seeing that stack trace I guess its something with your `AbstractEntity` class, that's custom one, right?

The changes in v5.4 were a bit breaking in this regard (just like TS 4.8 was 🤡), here is an example of how it can be done: 

https://stackblitz.com/edit/mikro-orm-repro-4xnnmk?file=test.ts
