### ISSUE TITLE
Access to `id` of `IdentifiedReference` potentially `undefined`

### ISSUE THREAD

**Issue by oliversalzburg** [mikro-orm/mikro-orm#1084]
**Describe the bug**
After upgrading to 4.3.0, access to the `id` property of an `IdentifiedReference` is no longer guaranteed to return the `id`. The field is potentially `undefined`.

**To Reproduce**
```typescript
const foo: IdentifiedReference<User, "id"> = Reference.create<User, "id">(user);
const bar:string = foo.id;
```

**Expected behavior**
The above code compiles.

**Additional context**
This doesn't happen in 4.2.0.

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 4.03 |
| mikro-orm | 4.3.0 |
| your-driver | ? |

**Comment by jsprw** [comment]
I noticed the same since upgrading to 4.3.0. I noticed it to happen when using find returning an unpopulated relation within a multi level populate (ent1 -> ent2 -> ent3 (the unpopulated identifiedreference)). It caused a lot of `prop = NULL` and `prop = <id>` in the same transaction and also causing DeadLockExceptions in Postgres. However, I was unable to create a stable reproduction.

Also,  the helper functions are also null sometimes (`ent3.load() is not a function`).

**Comment by B4nan** [comment]
This is on purpose, as discussed on slack. It is needed to make the assignment type checks works, otherwise assigning naked entity to reference property would pass (and that is not supported/allowed).

This is only about TS, the solution is to add `!` (non-null assertion operator). There is no way this would cause actual difference in how things are executed (so deadlocks are definitely not possible due to this change, compiled code is still the same).

**Comment by jsprw** [comment]
> There is no way this would cause actual difference in how things are executed (so deadlocks are definitely not possible due to this change, compiled code is still the same).

But, if you grab an entity (ent1) from the database that is multiple levels deep (ent2, ent3), you get at least one IdentifiedReference object. If you persist a new entity (ent4) that contains a relation to ent1, it tries to cascade ent2 and en3 as well, but as IdentifiedReferences are undefined out of nowhere, the changesetcomputer thinks that this should become a NULL and sets ent2 and ent3 to NULL on ent1.

This only happened since 4.3.0 and will try to make a reproduction for this but sometimes it happens and sometimes it does not..

**Comment by B4nan** [comment]
> but as IdentifiedReferences are undefined out of nowhere

Sounds like you are talking about something different, this issue is about the PK getter on the `Reference` wrapper. 

Not much changed in terms of how reference wrapper works. What did change is how 1:1 owners are persisted.

**Comment by jsprw** [comment]
> Sounds like you are talking about something different, this issue is about the PK getter on the `Reference` wrapper.
> 
> Not much changed in terms of how reference wrapper works. What did change is how 1:1 owners are persisted.

Ah, yes that might explain it. But how did it change? Is this a bug or on purpose?

**Comment by B4nan** [comment]
Well how can I know :] From your description I don't know basically anything :] Open new issue with reproduction, I need to see the code as well as entity definitions.

I can confirm something is not working 100% well, as I see some additional queries for 1:1 relations in my production app, but nothing broken, it just tries to first unset the relation and set it back right ahead.

Will close this, as this issue is about the PK getter and that works fine. Will be looking into the 1:1 thing hopefully today, but having your repro would be good as you might face different issue that what I see.

**Comment by jsprw** [comment]
> I can confirm something is not working 100% well, as I see some additional queries for 1:1 relations in my production app, but nothing broken, it just tries to first unset the relation and set it back right ahead.

This is exactly the same issue and those additional queries (caused by underlying relation not being loaded -> in changesetcomputer payload is the relation undefined) cause a deadlock exception under heavy load.
