### ISSUE TITLE
this.driver.getPlatform is not a function

### ISSUE THREAD

**Issue by milesje** [mikro-orm/mikro-orm#5412]
### Describe the bug

Error reported after upgrading to 6.1.12 from 5.9.X.

> 
> [Nest] 45391  - 04/03/2024, 2:32:09 PM   ERROR [ExceptionHandler] this.driver.getPlatform is not a function
> TypeError: this.driver.getPlatform is not a function
>     at new MikroORM (/home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@mikro-orm/core/MikroORM.js:95:105)
>     at Function.init (/home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@mikro-orm/core/MikroORM.js:35:21)
>     at Injector.instantiateClass (/home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/injector/injector.js:369:37)
>     at callback (/home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/injector/injector.js:65:34)
>     at Injector.resolveConstructorParams (/home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/injector/injector.js:144:24)
>     at Injector.loadInstance (/home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/injector/injector.js:70:13)
>     at Injector.loadProvider (/home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/injector/injector.js:97:9)
>     at /home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/injector/instance-loader.js:56:13
>     at async Promise.all (index 4)
>     at InstanceLoader.createInstancesOfProviders (/home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
>     at /home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/injector/instance-loader.js:40:13
>     at async Promise.all (index 5)
>     at InstanceLoader.createInstances (/home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/injector/instance-loader.js:39:9)
>     at InstanceLoader.createInstancesOfDependencies (/home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/injector/instance-loader.js:22:13)
>     at /home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/nest-factory.js:108:17
>     at Function.asyncRun (/home/jmiles/Code/Github/market-edge-ws-nestjs/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)

### Reproduction

NestJS package using .env for mikro-orm setup.

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.1.12

### Node.js version

v20.11.1

### Operating system

Linux (NixOS)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by milesje** [comment]
Here is an example repo
https://github.com/milesje/mikro-orm-6-error
